### PR TITLE
Events list

### PR DESCRIPTION
**Pull request by Yamini-L**
UI for Events Page which displays a mock set of events with a search bar and tags. Also included a temporary nav bar to help style the page.

### CODE REVIEW

**Review by DaveCSW — APPROVED** [review]
good

**Review by DaveCSW — APPROVED** [review]
looks good

**Review by DaveCSW — APPROVED** [review]
looks fine

**Review by gurnoor6 — APPROVED** [review]
Looks good! Approving for merge.

**Pull request merged**
